export interface CuratedProduct {
  id: string;
  slug: string;
  title: string;
  description: string;
  price_cents: number;
  currency: string;
  category: {
    slug: string;
    name: string;
  };
  tags: string[];
  width_cm: number;
  height_cm: number;
  depth_cm: number;
  primary_image_path: string;
  imageUrl: string;
  roomTypes: string[];
  style: string;
  material: string;
  is_active: boolean;
}

export const CURATED_CATEGORIES = [
  { slug: "seating", name: "Seating", count: 3 },
  { slug: "tables", name: "Tables", count: 3 },
  { slug: "storage", name: "Storage", count: 2 },
  { slug: "lighting", name: "Lighting", count: 2 },
  { slug: "decor", name: "Decor", count: 2 },
];

export const CURATED_ROOM_TYPES = [
  { id: "living-room", label: "Living Room" },
  { id: "bedroom", label: "Bedroom" },
  { id: "office", label: "Office & Study" },
  { id: "dining-room", label: "Dining Room" },
];

export const CURATED_STYLES = [
  { id: "minimal", label: "Minimalist" },
  { id: "mid-century", label: "Mid-Century" },
  { id: "earthy", label: "Earthy & Warm" },
  { id: "scandinavian", label: "Scandinavian" },
  { id: "industrial", label: "Industrial" },
];

export const CURATED_PRODUCTS: CuratedProduct[] = [
  {
    id: "prod-001",
    slug: "walnut-coffee-table",
    title: "Artisan Walnut Coffee Table",
    description: "Hand-crafted solid walnut coffee table featuring subtle bevelled edges, organically tapered legs, and natural oil finish that highlights rich grain patterns.",
    price_cents: 4500000,
    currency: "PKR",
    category: { slug: "tables", name: "Tables" },
    tags: ["style:mid-century", "color:warm-neutral", "material:wood", "room:living-room"],
    width_cm: 110,
    height_cm: 45,
    depth_cm: 60,
    primary_image_path: "walnut-coffee-table.jpg",
    imageUrl: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["living-room", "office"],
    style: "Mid-Century",
    material: "Solid Walnut Wood",
    is_active: true,
  },
  {
    id: "prod-002",
    slug: "linen-lounge-chair",
    title: "Nordic Bouclé Linen Lounge Chair",
    description: "Deep-seated lounge chair upholstered in breathable organic textured linen with sculpted solid white-oak framing for maximum comfort and tactile elegance.",
    price_cents: 6200000,
    currency: "PKR",
    category: { slug: "seating", name: "Seating" },
    tags: ["style:minimal", "color:neutral", "material:fabric", "room:living-room", "room:bedroom"],
    width_cm: 78,
    height_cm: 82,
    depth_cm: 80,
    primary_image_path: "linen-lounge-chair.jpg",
    imageUrl: "https://images.unsplash.com/photo-1580481077194-0d32c45f448b?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["living-room", "bedroom", "office"],
    style: "Minimalist",
    material: "Bouclé Linen & Solid Oak",
    is_active: true,
  },
  {
    id: "prod-003",
    slug: "brass-arc-floor-lamp",
    title: "Brushed Brass Arc Floor Lamp",
    description: "Gracefully counterbalanced floor lamp in spun brushed brass with a heavy marble stabilization base and a natural woven linen drum diffuser.",
    price_cents: 2850000,
    currency: "PKR",
    category: { slug: "lighting", name: "Lighting" },
    tags: ["style:mid-century", "color:gold", "material:metal", "room:living-room", "room:bedroom"],
    width_cm: 45,
    height_cm: 195,
    depth_cm: 95,
    primary_image_path: "brass-arc-floor-lamp.jpg",
    imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["living-room", "bedroom", "office"],
    style: "Mid-Century",
    material: "Brushed Brass & White Carrara Marble",
    is_active: true,
  },
  {
    id: "prod-004",
    slug: "oak-bookshelf",
    title: "Architectural Oak Bookshelf",
    description: "Five-tier open shelving unit constructed from sustainably harvested solid oak. Engineered with concealed mortise-and-tenon joints for clean vertical lines.",
    price_cents: 3900000,
    currency: "PKR",
    category: { slug: "storage", name: "Storage" },
    tags: ["style:minimal", "color:light-wood", "material:wood", "room:office", "room:living-room"],
    width_cm: 95,
    height_cm: 185,
    depth_cm: 36,
    primary_image_path: "oak-bookshelf.jpg",
    imageUrl: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["office", "living-room", "bedroom"],
    style: "Minimalist",
    material: "Solid Natural Oak",
    is_active: true,
  },
  {
    id: "prod-005",
    slug: "terracotta-vase-set",
    title: "Hand-Thrown Terracotta Vessel Trio",
    description: "Set of three sculptural terracotta vases with matte porous earthenware texture and warm ochre tones, individually shaped by master potters.",
    price_cents: 750000,
    currency: "PKR",
    category: { slug: "decor", name: "Decor" },
    tags: ["style:earthy", "color:terracotta", "material:ceramic", "room:living-room", "room:dining-room"],
    width_cm: 18,
    height_cm: 32,
    depth_cm: 18,
    primary_image_path: "terracotta-vase-set.jpg",
    imageUrl: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["living-room", "dining-room", "bedroom"],
    style: "Earthy & Warm",
    material: "Natural Matte Terracotta",
    is_active: true,
  },
  {
    id: "prod-006",
    slug: "platform-bed-frame",
    title: "Kyoto Low Platform Bed Frame",
    description: "Low-profile minimalist platform bed with an extended perimeter ledge and integrated floating headboard crafted in honey-stained oak veneer.",
    price_cents: 7800000,
    currency: "PKR",
    category: { slug: "seating", name: "Storage" },
    tags: ["style:minimal", "color:light-wood", "material:wood", "room:bedroom"],
    width_cm: 190,
    height_cm: 40,
    depth_cm: 215,
    primary_image_path: "platform-bed-frame.jpg",
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["bedroom"],
    style: "Minimalist",
    material: "Honey-Toned Oak & Beech Slats",
    is_active: true,
  },
  {
    id: "prod-007",
    slug: "travertine-dining-table",
    title: "Monolithic Travertine Dining Table",
    description: "Sculptural dining table with twin fluted cylindrical pedestal bases and an oval slab of unfilled Italian Roman travertine with softened honed edge.",
    price_cents: 9500000,
    currency: "PKR",
    category: { slug: "tables", name: "Tables" },
    tags: ["style:minimal", "color:warm-neutral", "material:stone", "room:dining-room"],
    width_cm: 200,
    height_cm: 76,
    depth_cm: 100,
    primary_image_path: "travertine-dining-table.jpg",
    imageUrl: "https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["dining-room"],
    style: "Minimalist",
    material: "Natural Italian Travertine",
    is_active: true,
  },
  {
    id: "prod-008",
    slug: "leather-safari-armchair",
    title: "Caramel Saddle Leather Safari Chair",
    description: "Iconic sling safari armchair crafted with vegetable-tanned top-grain saddle leather and a kiln-dried solid ash wooden framework.",
    price_cents: 5400000,
    currency: "PKR",
    category: { slug: "seating", name: "Seating" },
    tags: ["style:mid-century", "color:caramel", "material:leather", "room:living-room", "room:office"],
    width_cm: 72,
    height_cm: 78,
    depth_cm: 70,
    primary_image_path: "leather-safari-armchair.jpg",
    imageUrl: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["living-room", "office"],
    style: "Mid-Century",
    material: "Full-Grain Leather & Ash Wood",
    is_active: true,
  },
  {
    id: "prod-009",
    slug: "matte-black-pendant-light",
    title: "Dome Matte Black Pendant Light",
    description: "Industrial spun aluminum pendant fixture with a matte textured black exterior and an incandescent warm brass reflective interior bowl.",
    price_cents: 1850000,
    currency: "PKR",
    category: { slug: "lighting", name: "Lighting" },
    tags: ["style:industrial", "color:black", "material:metal", "room:dining-room", "room:living-room"],
    width_cm: 40,
    height_cm: 30,
    depth_cm: 40,
    primary_image_path: "matte-black-pendant-light.jpg",
    imageUrl: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["dining-room", "living-room", "office"],
    style: "Industrial",
    material: "Spun Aluminum & Antique Brass",
    is_active: true,
  },
  {
    id: "prod-010",
    slug: "woven-wool-jute-rug",
    title: "Hand-Knotted Organic Wool & Jute Rug",
    description: "Dense, tactile area rug woven with un-dyed New Zealand highland wool interwoven with natural golden jute strands in a geometric rib pattern.",
    price_cents: 3600000,
    currency: "PKR",
    category: { slug: "decor", name: "Decor" },
    tags: ["style:earthy", "color:neutral", "material:wool", "room:living-room", "room:bedroom"],
    width_cm: 240,
    height_cm: 2,
    depth_cm: 170,
    primary_image_path: "woven-wool-jute-rug.jpg",
    imageUrl: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["living-room", "bedroom", "dining-room"],
    style: "Earthy & Warm",
    material: "Pure Wool & Natural Jute",
    is_active: true,
  },
  {
    id: "prod-011",
    slug: "walnut-credenza-sideboard",
    title: "Slatted Walnut Media Credenza",
    description: "Low-profile media console with acoustic slatted tambour doors, soft-close drawers, and integrated cable routing for media devices.",
    price_cents: 8200000,
    currency: "PKR",
    category: { slug: "storage", name: "Storage" },
    tags: ["style:mid-century", "color:warm-neutral", "material:wood", "room:living-room"],
    width_cm: 180,
    height_cm: 58,
    depth_cm: 45,
    primary_image_path: "walnut-credenza-sideboard.jpg",
    imageUrl: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["living-room", "dining-room"],
    style: "Mid-Century",
    material: "Solid Walnut & Brass Hardware",
    is_active: true,
  },
  {
    id: "prod-012",
    slug: "minimalist-oak-writing-desk",
    title: "Cantilever Oak Writing Desk",
    description: "Streamlined modern work desk with dual felt-lined stationery drawers, chamfered edge profile, and solid oak trestle legs.",
    price_cents: 5100000,
    currency: "PKR",
    category: { slug: "tables", name: "Tables" },
    tags: ["style:scandinavian", "color:light-wood", "material:wood", "room:office"],
    width_cm: 130,
    height_cm: 75,
    depth_cm: 65,
    primary_image_path: "minimalist-oak-writing-desk.jpg",
    imageUrl: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80",
    roomTypes: ["office", "bedroom"],
    style: "Scandinavian",
    material: "Solid White Oak",
    is_active: true,
  },
];
